<a href="https://colab.research.google.com/github/Andru-1987/data_science_ii_96085/blob/main/05_semana/clase_05_data_wrangling_ii.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
from google.colab import userdata

In [5]:
! pip install SQLAlchemy

Requirement already satisfied: SQLAlchemy in /usr/local/lib/python3.12/dist-packages (2.0.52)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy) (3.5.5)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from SQLAlchemy) (4.16.0)

In [6]:
from sqlalchemy import create_engine, text

In [7]:
DATABASE_URL:str = userdata.get('NEON_PG_DATABASE')

In [8]:
engine = create_engine(DATABASE_URL)

In [9]:
query = "SELECT * FROM ecommerce_transacciones"

In [10]:
with engine.connect() as connection:
    df_ecommerce = pd.read_sql_query(sql=text( query), con=connection)

In [11]:
df_ecommerce

,id_transaccion,cliente_zona,categoria,monto_usd,estado_envio,fecha_transaccion,created_at
0,1001,Norte,Electrónica,250.0,Entregado,2026-01-15,2026-08-19 11:19:42.681088
1,1002,Sur,Hogar,50.0,En tránsito,2026-01-15,2026-08-19 11:19:42.681088
2,1003,Este,Ropa,30.0,Entregado,2026-01-16,2026-08-19 11:19:42.681088
3,1004,Norte,Electrónica,120.0,Devuelto,2026-01-16,2026-08-19 11:19:42.681088
4,1005,Oeste,Ropa,45.0,Entregado,2026-01-17,2026-08-19 11:19:42.681088
...,...,...,...,...,...,...,...
95,1096,Este,Electrónica,460.0,Entregado,2026-03-04,2026-08-19 11:19:42.681088
96,1097,Oeste,Hogar,108.0,Entregado,2026-03-05,2026-08-19 11:19:42.681088
97,1098,Norte,Electrónica,270.0,En tránsito,2026-03-05,2026-08-19 11:19:42.681088
98,1099,Sur,Hogar,238.0,Entregado,2026-03-06,2026-08-19 11:19:42.681088
99,1100,Este,Ropa,36.0,Entregado,2026-03-06,2026-08-19 11:19:42.681088

In [12]:
df_ecommerce.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_transaccion     100 non-null    int64
 1   cliente_zona       100 non-null    object
 2   categoria          100 non-null    object
 3   monto_usd          100 non-null    float64
 4   estado_envio       100 non-null    object
 5   fecha_transaccion  100 non-null    object
 6   created_at         100 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(4)
memory usage: 5.6+ KB

In [14]:
df_ecommerce.describe().T

,count,mean,min,25%,50%,75%,max,std
id_transaccion,100.0,1050.5,1001.0,1025.75,1050.5,1075.25,1100.0,29.011492
monto_usd,100.0,189.05,30.0,77.25,160.0,270.0,560.0,133.74802
created_at,100,2026-08-19 11:19:42.681087744,2026-08-19 11:19:42.681088,2026-08-19 11:19:42.681088,2026-08-19 11:19:42.681088,2026-08-19 11:19:42.681088,2026-08-19 11:19:42.681088,NaN

# deduplicacion de datos

In [16]:
df_ecommerce.duplicated()
df_ecommerce.drop_duplicates(inplace=True)
df_ecommerce

,id_transaccion,cliente_zona,categoria,monto_usd,estado_envio,fecha_transaccion,created_at
0,1001,Norte,Electrónica,250.0,Entregado,2026-01-15,2026-08-19 11:19:42.681088
1,1002,Sur,Hogar,50.0,En tránsito,2026-01-15,2026-08-19 11:19:42.681088
2,1003,Este,Ropa,30.0,Entregado,2026-01-16,2026-08-19 11:19:42.681088
3,1004,Norte,Electrónica,120.0,Devuelto,2026-01-16,2026-08-19 11:19:42.681088
4,1005,Oeste,Ropa,45.0,Entregado,2026-01-17,2026-08-19 11:19:42.681088
...,...,...,...,...,...,...,...
95,1096,Este,Electrónica,460.0,Entregado,2026-03-04,2026-08-19 11:19:42.681088
96,1097,Oeste,Hogar,108.0,Entregado,2026-03-05,2026-08-19 11:19:42.681088
97,1098,Norte,Electrónica,270.0,En tránsito,2026-03-05,2026-08-19 11:19:42.681088
98,1099,Sur,Hogar,238.0,Entregado,2026-03-06,2026-08-19 11:19:42.681088
99,1100,Este,Ropa,36.0,Entregado,2026-03-06,2026-08-19 11:19:42.681088

# Transformacions de datos

In [18]:
DOLAR_OFICIAL:int = 1_515
PERCEPCION:float = 0.3
IVA:float = 1.21

In [19]:
def aplicacion_cambio_a_pesos(monto: float) -> float:
    return monto * DOLAR_OFICIAL - monto * PERCEPCION - monto * IVA

In [20]:
df_ecommerce['monto_pesos_argentinos'] = df_ecommerce['monto_usd'].apply(aplicacion_cambio_a_pesos)

In [21]:
df_ecommerce.head()

,id_transaccion,cliente_zona,categoria,monto_usd,estado_envio,fecha_transaccion,created_at,monto_pesos_argentinos
0,1001,Norte,Electrónica,250.0,Entregado,2026-01-15,2026-08-19 11:19:42.681088,378372.50
1,1002,Sur,Hogar,50.0,En tránsito,2026-01-15,2026-08-19 11:19:42.681088,75674.50
2,1003,Este,Ropa,30.0,Entregado,2026-01-16,2026-08-19 11:19:42.681088,45404.70
3,1004,Norte,Electrónica,120.0,Devuelto,2026-01-16,2026-08-19 11:19:42.681088,181618.80
4,1005,Oeste,Ropa,45.0,Entregado,2026-01-17,2026-08-19 11:19:42.681088,68107.05

In [22]:
df_ecommerce.estado_envio.value_counts()

estado_envio
Entregado      69
En tránsito    16
Devuelto       15
Name: count, dtype: int64

In [23]:
dict_datos: dict = {
    "Entregado": 1,
    "En tránsito": 0,
    "Devuelto": 2
}

In [24]:
df_ecommerce['estado_envio'] = df_ecommerce['estado_envio'].map(dict_datos)

In [25]:
df_ecommerce.estado_envio.value_counts()

estado_envio
1    69
0    16
2    15
Name: count, dtype: int64

## Los usuarios que hicieron compras VIP

In [27]:
BASE_COMPRA_USD: int = 100
ESTADO_ENVIO_ENTREGADO: int = 1

In [28]:
mascara_vip = ( df_ecommerce.monto_usd >= BASE_COMPRA_USD ) & ( df_ecommerce.estado_envio == ESTADO_ENVIO_ENTREGADO )

In [30]:
mascara_vip.value_counts()

False    54
True     46
Name: count, dtype: int64

In [32]:
usuarios_vip = df_ecommerce[mascara_vip]
usuarios_vip.head()

,id_transaccion,cliente_zona,categoria,monto_usd,estado_envio,fecha_transaccion,created_at,monto_pesos_argentinos
0,1001,Norte,Electrónica,250.0,1,2026-01-15,2026-08-19 11:19:42.681088,378372.5
5,1006,Norte,Hogar,180.0,1,2026-01-17,2026-08-19 11:19:42.681088,272428.2
6,1007,Sur,Electrónica,320.0,1,2026-01-18,2026-08-19 11:19:42.681088,484316.8
8,1009,Oeste,Electrónica,210.0,1,2026-01-19,2026-08-19 11:19:42.681088,317832.9
11,1012,Este,Electrónica,450.0,1,2026-01-20,2026-08-19 11:19:42.681088,681070.5

In [34]:
columas_indexar:list[str] = ['cliente_zona', 'categoria']

In [36]:
df_indexado_e_commerce = df_ecommerce.set_index(columas_indexar)

In [39]:
df_indexado_e_commerce.sort_index(inplace=True)

In [40]:
df_indexado_e_commerce

                          id_transaccion  monto_usd  estado_envio  \
cliente_zona categoria
Este         Electrónica            1012      450.0             1
             Electrónica            1024      390.0             2
             Electrónica            1032      420.0             1
             Electrónica            1048      560.0             1
             Electrónica            1060      380.0             1
...                                  ...        ...           ...
Sur          Ropa                   1023       70.0             1
             Ropa                   1031       35.0             1
             Ropa                   1047       78.0             1
             Ropa                   1071       82.0             1
             Ropa                   1095       88.0             1

                         fecha_transaccion                 created_at  \
cliente_zona categoria
Este         Electrónica        2026-01-20 2026-08-19 11:19:42.681088
             Electrónica        2026-01-26 2026-08-19 11:19:42.681088
             Electrónica        2026-01-30 2026-08-19 11:19:42.681088
             Electrónica        2026-02-08 2026-08-19 11:19:42.681088
             Electrónica        2026-02-14 2026-08-19 11:19:42.681088
...                                    ...                        ...
Sur          Ropa               2026-01-26 2026-08-19 11:19:42.681088
             Ropa               2026-01-30 2026-08-19 11:19:42.681088
             Ropa               2026-02-08 2026-08-19 11:19:42.681088
             Ropa               2026-02-20 2026-08-19 11:19:42.681088
             Ropa               2026-03-04 2026-08-19 11:19:42.681088

                          monto_pesos_argentinos
cliente_zona categoria
Este         Electrónica               681070.50
             Electrónica               590261.10
             Electrónica               635665.80
             Electrónica               847554.40
             Electrónica               575126.20
...                                          ...
Sur          Ropa                      105944.30
             Ropa                       52972.15
             Ropa                      118052.22
             Ropa                      124106.18
             Ropa                      133187.12

[100 rows x 6 columns]

## Reporte de ventas

In [41]:
reporte_ventas = pd.pivot_table(
    data=df_ecommerce,
    values='monto_usd',
    index='cliente_zona',
    columns='categoria',
    aggfunc='mean'
)

In [42]:
reporte_ventas

categoria     Electrónica       Hogar       Ropa
cliente_zona
Este           440.000000  124.375000  43.555556
Norte          220.000000  181.666667  70.714286
Oeste          273.888889  101.125000  56.285714
Sur            406.250000  199.363636  73.666667

In [43]:
reporte_plano = reporte_ventas.reset_index()

In [44]:
reporte_plano

categoria cliente_zona  Electrónica       Hogar       Ropa
0                 Este   440.000000  124.375000  43.555556
1                Norte   220.000000  181.666667  70.714286
2                Oeste   273.888889  101.125000  56.285714
3                  Sur   406.250000  199.363636  73.666667

In [45]:
pd.melt(
    reporte_plano,
    id_vars = ['cliente_zona'],
    value_vars= "Electrónica,Hogar,Ropa".split(','),
    var_name='categoria',
    value_name='ticket_promedio'
)

   cliente_zona    categoria  ticket_promedio
0          Este  Electrónica       440.000000
1         Norte  Electrónica       220.000000
2         Oeste  Electrónica       273.888889
3           Sur  Electrónica       406.250000
4          Este        Hogar       124.375000
5         Norte        Hogar       181.666667
6         Oeste        Hogar       101.125000
7           Sur        Hogar       199.363636
8          Este         Ropa        43.555556
9         Norte         Ropa        70.714286
10        Oeste         Ropa        56.285714
11          Sur         Ropa        73.666667

### Dataframe -> melt y pivot

In [46]:
df_ventas = pd.DataFrame({
    'Sucursal': ['A', 'B', 'C'],
    'Enero': [100, 150, 200],
    'Febrero': [120, 160, 220],
    'Marzo': [110, 170, 210]
})

df_ventas

  Sucursal  Enero  Febrero  Marzo
0        A    100      120    110
1        B    150      160    170
2        C    200      220    210

In [47]:
df_vertical = pd.melt(
    df_ventas, #  data que yo trabajar
    id_vars=['Sucursal'],  # col que se mantiene fija
    value_vars=['Enero', 'Febrero', 'Marzo'], # col que se convierten en filas
    var_name='Mes Apilado', # nombre de columna de variables
    value_name='Ventas' # nombre de la columna con los valores
)

In [48]:
df_vertical

  Sucursal Mes Apilado  Ventas
0        A       Enero     100
1        B       Enero     150
2        C       Enero     200
3        A     Febrero     120
4        B     Febrero     160
5        C     Febrero     220
6        A       Marzo     110
7        B       Marzo     170
8        C       Marzo     210

In [50]:
df_vertical.pivot(
    index='Sucursal',
    columns='Mes Apilado',
    values='Ventas'
)

Mes Apilado  Enero  Febrero  Marzo
Sucursal
A              100      120    110
B              150      160    170
C              200      220    210